# Generated by Django 3.1.3 on 2022-07-15 11:44

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220715_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_image',
            name='image',
            field=models.ImageField(upload_to=auctions.models.auction_image_handler),
        ),
    ]
