# Generated by Django 3.1.3 on 2022-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220715_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Auction_listing'),
        ),
    ]
